---
- name: restart flink
  shell: /bin/systemctl daemon-reload
  notify:
    - restart flink jobmanager
    - restart flink taskmanager

- name: restart flink jobmanager
  service: name=flink-jobmanager.service state=restarted
  notify: restart rsyslog
  when: master == true

- name: restart flink taskmanager
  service: name=flink-taskmanager.service state=restarted
  notify: restart rsyslog

- name: restart rsyslog
  service: name=rsyslog state=restarted
